set(CTEST_SOURCE_DIRECTORY "$ENV{GITHUB_WORKSPACE}")
set(CTEST_BINARY_DIRECTORY "${CTEST_SOURCE_DIRECTORY}/build")

set(CTEST_SITE "github.com")

set(CTEST_BUILD_NAME "github-${GITHUB_RUNNER_OS}-default")

if (GITHUB_RUNNER_OS STREQUAL "Linux")
	set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
elseif (GITHUB_RUNNER_OS STREQUAL "macOS")
	set(CTEST_CMAKE_GENERATOR "Xcode")
elseif (GITHUB_RUNNER_OS STREQUAL "Windows")
	set(CTEST_CMAKE_GENERATOR "Visual Studio 16 2019")
endif()

set(CTEST_BUILD_CONFIGURATION "Debug")

set(WITH_MEMCHECK TRUE)
set(CTEST_BUILD_OPTIONS "")
set(WITH_COVERAGE FALSE)

find_program(CTEST_GIT_COMMAND NAMES git)
find_program(CTEST_COVERAGE_COMMAND NAMES gcov)
find_program(CTEST_MEMORYCHECK_COMMAND NAMES valgrind)

set(CTEST_UPDATE_COMMAND "${CTEST_GIT_COMMAND}")

include(${CTEST_SCRIPT_DIRECTORY}/common.cmake)
