set(CTEST_SOURCE_DIRECTORY "$ENV{TRAVIS_BUILD_DIR}")
set(CTEST_BINARY_DIRECTORY "${CTEST_SOURCE_DIRECTORY}/build")

set(CTEST_SITE "travis-ci.com")
set(CTEST_BUILD_NAME "$ENV{TRAVIS_OS_NAME}-$ENV{TRAVIS_COMPILER}-default")

set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
set(CTEST_BUILD_CONFIGURATION "Debug")

set(WITH_MEMCHECK TRUE)

set(TRAVIS_COMPILER "$ENV{TRAVIS_COMPILER}")
if (TRAVIS_COMPILER STREQUAL "gcc")
	set(CTEST_BUILD_OPTIONS "-DWITH_COVERAGE:BOOL=ON")
	set(WITH_COVERAGE TRUE)
else()
	set(CTEST_BUILD_OPTIONS "")
	set(WITH_COVERAGE FALSE)
endif()

find_program(CTEST_GIT_COMMAND NAMES git)
find_program(CTEST_COVERAGE_COMMAND NAMES gcov)
find_program(CTEST_MEMORYCHECK_COMMAND NAMES valgrind)

set(CTEST_UPDATE_COMMAND "${CTEST_GIT_COMMAND}")

include(${CTEST_SCRIPT_DIRECTORY}/common.cmake)
