name: C/C++ CI

on: [push]

env:
  GTest_ROOT: $HOME/googletest

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Install Google Test
      run: |
        git clone --single-branch --branch v1.8.x https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake -DBUILD_GMOCK=FALSE -DCMAKE_INSTALL_PREFIX=$GTest_ROOT ..
        cmake --build .
        cmake --build . --target install
        cd $TRAVIS_BUILD_DIR

    - name: Build & Test
      run: ctest -S ci/github.cmake
